### ISSUE TITLE
 open a exist excel file and print out it 

### ISSUE THREAD

**Issue by liufeijin** [j2doll/QXlsx#12]
Sorry for my bad English.
My mean is how to open a exist excel file and print out it on paper.
Some times a excel file has many sheets , maybe we only want to print out i sheet only.
Does QXlsx provide this print function? ( or Qxlnt ? Qlibxlsxwriter? )
best regards,
jeff

**Comment by j2doll** [comment]
Dear liufeijin:
QXlsx and other libraries do not support print on paper.
The content has been identified in the issue as an enchantment.
Issue is duplicated.
https://github.com/j2doll/QXlsx/issues/9

**Comment by liufeijin** [comment]
Dear j2doll
Do you have any plane to complete it or any suggestion?

**Comment by liufeijin** [comment]
https://github.com/Alexhuszagh/libxlsxwriterpp/blob/master/src/worksheet.cpp
it seems can print out excel in this project

**Comment by j2doll** [comment]
Issue is duplicated.
#9
