### ISSUE TITLE
suggestion for  excel file print out on paper

### ISSUE THREAD

**Issue by liufeijin** [j2doll/QXlsx#13]
Hi your projects QXlsx and Qlibxlsxwriter can read and write excel file well.
So  i think maybe has a easy way to call some windows API and print out the excel file( of course OS to be installed office software ), because for a excel file we can click the "print item " in the pop menu  by clicking   right button  of mouse .

**Comment by j2doll** [comment]
Dear liufeijin:
If you use libraries on Windows, your way is okay. Why not!
But I am aiming to support cross platform.
So I try to use only cross-platform tools like Qt whenever possible.
