### ISSUE TITLE
Write excel warning by QXlsx   new problem

### ISSUE THREAD

**Issue by liufeijin** [j2doll/QXlsx#15]
I got the warning when i write a excel (PLS refer attachment) as below codes

 QXlsx::Document xlsx("d:/V1805133.xlsx");
    if (!xlsx.isLoadPackage())
    {
        qDebug() << "Failed to load data.xlsx";

    }else{
        if(xlsx.selectSheet("A")){

            qDebug() << xlsx.read("A1"); // QVariant(QString, "A1DATA")
            qDebug() << xlsx.read("A2"); // QVariant(Invalid)
            qDebug() << xlsx.read("B1"); // QVariant(QString, "B1DATA")
            qDebug() << xlsx.read("B2"); // QVariant(QString, "B2DATA")

            xlsx.write("E5", "Hello ");

            xlsx.save();
        }
    }
if the excel file  include a drawing , after writing as above , the drawing will be lose.

**Comment by liufeijin** [comment]
very sad , maybe i must to try other lib.

**Comment by liufeijin** [comment]
i want to try Qlibxlsxwriter  but fail  as the zip.h can't find . 
and try to set it . fail

**Comment by j2doll** [comment]
Dear liufeijin:

- I do not know the cause of the case yet. https://github.com/j2doll/QXlsx/issues/15#issue-371363811

- If you wanna use [Qlibxlsxwriter](https://github.com/j2doll/Qlibxlsxwriter), you must install [zlib](https://zlib.net/).  See [how to setup](https://github.com/j2doll/Qlibxlsxwriter#how-to-setup).
  And if you use MSYS2 or Visual Studio for Qlibxlsxwriter, See [tested environments](https://github.com/j2doll/Qlibxlsxwriter/blob/master/TestEnv.md#tested-environments) .

- If the solution still does not work, try [Qxlnt](https://github.com/j2doll/Qxlnt).  

- Each library does not fully support [ECMA 376](http://www.ecma-international.org/publications/standards/Ecma-376.htm).

**Comment by liufeijin** [comment]
Dear J2doll
 I found  which different will case this bug
//////////////////////////////////////////////
I rename the  excel file V1805133.XLSX to V1805133.ZIP and extract to V1805133befor
after writing by QXlsx (don't open and reapair by office)  rename to V1805133.zip and extract to V1805133after.

I replace 2 files from v1805133before folder to  v1805133after folder 
1  [Content_Types].xml
2  /xl/drawing1.xml

the excel file will be normal .

So the problem is QXls writs the xml file in wrong format or lose some thing . i think this maybe can be fixed .
Cloud you have a look ?

**Comment by liufeijin** [comment]
in the file  [Content_Types].xml   it is lose below row 

<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>

**Comment by liufeijin** [comment]
Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/

**Comment by liufeijin** [comment]
and this row is wrong , to be deleted whole row
Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/

**Comment by liufeijin** [comment]
the  file  /xl/drawing1.xml  is lose  beleow 

<xdr:sp macro="" textlink="">
<xdr:nvSpPr>
<xdr:cNvPr id="2" name=" 1"/>
<xdr:cNvSpPr/></xdr:nvSpPr>

**Comment by liufeijin** [comment]
after modify  the 2 file  as above , QXls will be ok

**Comment by liufeijin** [comment]
The /xl/workbook.xml  are double row  , below row  will be change by /docProps/app.xml
Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/

**Comment by liufeijin** [comment]
void DrawingTwoCellAnchor::saveToXml(QXmlStreamWriter &writer) const
{
    writer.writeStartElement(QStringLiteral("xdr:twoCellAnchor"));
    writer.writeAttribute(QStringLiteral("editAs"), QStringLiteral("oneCell"));

    saveXmlMarker(writer, from, QStringLiteral("xdr:from"));
    saveXmlMarker(writer, to, QStringLiteral("xdr:to"));

    saveXmlObject(writer);

    writer.writeEmptyElement(QStringLiteral("xdr:clientData"));
    writer.writeEndElement(); //xdr:twoCellAnchor
}
is for writing /xl/drawing1.xml  

the    saveXmlObject(writer);  has problem , it dosn't save any thing
below is lost
-<xdr:sp textlink="" macro="">


-<xdr:nvSpPr>

<xdr:cNvPr name=" 1" id="2"/>

<xdr:cNvSpPr/>

</xdr:nvSpPr>

<xdr:spPr/>

</xdr:sp>

**Comment by liufeijin** [comment]
in xlsxdrawinganchor.cpp
void DrawingAbsoluteAnchor::saveToXml(QXmlStreamWriter &writer) const
{
    writer.writeStartElement(QStringLiteral("xdr:absoluteAnchor"));
    saveXmlPos(writer, pos);
    saveXmlExt(writer, ext);

    saveXmlObject(writer);

    writer.writeEmptyElement(QStringLiteral("xdr:clientData"));
    writer.writeEndElement(); //xdr:absoluteAnchor
}
to be add  xdr:nvSpPr ...  like as  ( but below is  xdr:nuPicPr)

 writer.writeStartElement(QStringLiteral("xdr:nvPicPr"));
    writer.writeEmptyElement(QStringLiteral("xdr:cNvPr"));
    writer.writeAttribute(QStringLiteral("id"), QString::number(m_id));
    writer.writeAttribute(QStringLiteral("name"), QStringLiteral("Picture %1").arg(m_id));

    writer.writeStartElement(QStringLiteral("xdr:cNvPicPr"));
    writer.writeEmptyElement(QStringLiteral("a:picLocks"));
    writer.writeAttribute(QStringLiteral("noChangeAspect"), QStringLiteral("1"));
    writer.writeEndElement(); //xdr:cNvPicPr

    writer.writeEndElement(); //xdr:nvPicPr

**Comment by liufeijin** [comment]
i have repaired this error,  and updated the code , PLS check

**Comment by j2doll** [comment]
Dear @liufeijin:
- Your feedback has been reflected. Thank you for your advice.
- For more information, see: https://github.com/j2doll/QXlsx/pull/16#issue-223910693
