### ISSUE TITLE
very bad news, any shape in excel file will be lose after writing by QXls

### ISSUE THREAD

**Issue by liufeijin** [j2doll/QXlsx#17]
if the excel has drawing (shape) , after writing they will be lose .
as below items will be in /xl/drawings/drwawing1.xml  

-<xdr:twoCellAnchor editAs="absolute">

-<xdr:from>

<xdr:col>1</xdr:col>

<xdr:colOff>23813</xdr:colOff>

<xdr:row>7</xdr:row>

<xdr:rowOff>0</xdr:rowOff>

</xdr:from>

-<xdr:to>

<xdr:col>16</xdr:col>

<xdr:colOff>219075</xdr:colOff>

<xdr:row>21</xdr:row>

<xdr:rowOff>71438</xdr:rowOff>

</xdr:to>

-<xdr:sp textlink="" macro="">

-<xdr:nvSpPr>

<xdr:cNvPr name="矩形 6" id="7"/>

<xdr:cNvSpPr/>

</xdr:nvSpPr>

-<xdr:spPr>

-<a:xfrm>

<a:off y="1543050" x="452438"/>

<a:ext cy="2871788" cx="6110287"/>

</a:xfrm>

-<a:prstGeom prst="rect">

<a:avLst/>

</a:prstGeom>

-<a:blipFill rotWithShape="1" dpi="0">

-<a:blip r:embed="rId1" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">

-<a:extLst>

-<a:ext uri="{28A0092B-C50C-407E-A947-70E740481C1C}">

<a14:useLocalDpi val="0" xmlns:a14="http://schemas.microsoft.com/office/drawing/2010/main"/>

</a:ext>

</a:extLst>

</a:blip>

<a:srcRect/>

-<a:stretch>

<a:fillRect/>

</a:stretch>

</a:blipFill>

<a:ln w="3175"/>

</xdr:spPr>

-<xdr:style>

-<a:lnRef idx="2">

-<a:schemeClr val="accent1">

<a:shade val="50000"/>

</a:schemeClr>

</a:lnRef>

-<a:fillRef idx="1">

<a:schemeClr val="accent1"/>

</a:fillRef>

-<a:effectRef idx="0">

<a:schemeClr val="accent1"/>

</a:effectRef>

-<a:fontRef idx="minor">

<a:schemeClr val="lt1"/>

</a:fontRef>

</xdr:style>

-<xdr:txBody>

<a:bodyPr anchor="t" rtlCol="0" horzOverflow="clip" vertOverflow="clip"/>

<a:lstStyle/>

-<a:p>

<a:pPr algn="l"/>

<a:endParaRPr lang="zh-CN" sz="1100" altLang="en-US"/>

</a:p>

</xdr:txBody>

</xdr:sp>

Seems QXls miss to writ the shape item.  
Could you improve it?  I have no any information about it.
best regards,
jeff

**Comment by j2doll** [comment]
Dear @liufeijin

Thank you very much for finding the bug.

I am currently very busy with personal problems, it is difficult to promise when it will solve the problem.
Of course, if I have free time, I will start working, sometime.

If anyone can do it, anyone can participate in debugging.
This project is open source and anyone can participate in debugging and editing!

If you need this feature and are very busy, 
I recommend you use an alternative project. (Such as [Qxlnt](https://github.com/j2doll/Qxlnt))

**Comment by liufeijin** [comment]
Dear j2doll
I think Qxlnt has no this function also.
I check the xlsxdrawinganchor.cpp in QXlsx project and found the 

void DrawingAnchor::loadXmlObjectShape(QXmlStreamReader &reader)
{
    Q_UNUSED(reader)
}

void DrawingAnchor::saveXmlObjectShape(QXmlStreamWriter &writer) const
{
    Q_UNUSED(writer)
}
these are not completed .  i think if complete it will be ok.

**Comment by liufeijin** [comment]
> Dear @liufeijin
> 
> Thank you very much for finding the bug.
> 
> I am currently very busy with personal problems, it is difficult to promise when it will solve the problem.
> Of course, if I have free time, I will start working, sometime.
> 
> If anyone can do it, anyone can participate in debugging.
> This project is open source and anyone can participate in debugging and editing!
> 
> If you need this feature and are very busy,
> I recommend you use an alternative project. (Such as [Qxlnt](https://github.com/j2doll/Qxlnt))

I check and have tried QXlnt , it doesn't have drawing item, and will lose a lot of format.
Upon, QXLsx is the best one

**Comment by liufeijin** [comment]
It is very clear on writing drawing xml item in Qlibxlsxwrite project.
But it hasn't the read xml items.  very sad, can't find a document

**Comment by liufeijin** [comment]
cost 3 whole days , i have got the function, but i know my code is very ugly.
i think pass all code in a package to you  is better as i change many place .
PLS tidy it first and then upload to your project.

**Comment by j2doll** [comment]
Dear @liufeijin

I am very fortunate to hear that you have solved some problems.
I think we need to take a little more time, to solve the problem.

There is no ugly code. Every code is great. 😃

**Comment by liufeijin** [comment]
Dear J2doll
I have update the codes in your project. seems can't see the pull requests？

**Comment by liufeijin** [comment]
I have seed all code in package to you gmail. Pls Check it. 
best regards,
liufeijin

**Comment by j2doll** [comment]
Dear @liufeijin

I have not seen your 'Pull Request'.

And I do not use my github email for projects.
Maybe your email has been spam processed. 😢 

Please use issues and 'Pull Request'.

**Comment by liufeijin** [comment]
Dear J2doll
I have send it to your google gmail. PLS check it. I have forked your project also, it is new in my branch.
Sorry, i am green hand for using github. :)
Best regards,
liufeijin

**Comment by j2doll** [comment]
Dear @liufeijin

I check (your code](https://github.com/j2doll/QXlsx/pull/19).
And I did not compile the code, so I left a comment. [https://github.com/j2doll/QXlsx/pull/19#pullrequestreview-169623201](https://github.com/j2doll/QXlsx/pull/19#pullrequestreview-169623201)

**Comment by liufeijin** [comment]
QT5.11.3 VS2017 
PLS check my branch ,it is ok
this bug can be closed

**Comment by j2doll** [comment]
Ok. I'll close this issue.
