### ISSUE TITLE
Sources do not compile: CellLocation constructor error

### ISSUE THREAD

**Issue by netnazgul** [j2doll/QXlsx#21]
https://github.com/j2doll/QXlsx/blob/dc31d0ff00425481d037863c191cf96e2c8d34ec/QXlsx/source/xlsxcelllocation.cpp#L20

> 3rdparty\QXlsx\QXlsx\source\xlsxcelllocation.cpp:20: error: C2679: binary '=' : no operator found which takes a right-hand operand of type 'int' (or there is no acceptable conversion)
C:\Qt\5.5\msvc2013\include\QtCore/qsharedpointer_impl.h(330): could be 'QSharedPointer<QXlsx::Cell> &QSharedPointer<QXlsx::Cell>::operator =(QSharedPointer<QXlsx::Cell> &&)'
C:\Qt\5.5\msvc2013\include\QtCore/qsharedpointer_impl.h(317): or       'QSharedPointer<QXlsx::Cell> &QSharedPointer<QXlsx::Cell>::operator =(const QSharedPointer<QXlsx::Cell> &)'
while trying to match the argument list '(QSharedPointer<QXlsx::Cell>, int)'

MSVC2013 x86 is used to compile the project.

**Comment by j2doll** [comment]
Dear @netnazgul :
I do not currently have a VS2013 environment.
Please try the following and tell me the results.

- before
```cpp
CellLocation::CellLocation()
{
    col = -1;
    row = -1;

    cell = NULL;
}
```

- after
```cpp
CellLocation::CellLocation()
{
    col = -1;
    row = -1;

    cell = nullptr;
}
```

If the environment of VS is configured for me, I will try later.

**Comment by netnazgul** [comment]
Qt 5.5.1 : MSVC2013 + 32bit + qmake 3.0
Not sure what the exact msvc version is, I think it was Windows SDK 8.1.

Neither NULL nor nullptr work; I've just commented the line out to make it build.

I think, you should use `cell.clear();` here instead as it is the correct way to use QSharedPointer.
