### ISSUE TITLE
What's time add   xlsxcelllocation.h and xlsxcelllocation.cpp.?

### ISSUE THREAD

**Issue by liufeijin** [j2doll/QXlsx#23]
my package doesn't have this xlsxcelllocation.h and xlsxcelllocation.cpp.?
what function is it?

**Comment by j2doll** [comment]
Dear @liufeijin
I have added these files in version 1.3.5.
https://github.com/j2doll/QXlsx/releases/tag/v1.3.5
https://github.com/j2doll/QXlsx/releases/tag/v1.3.4
