### ISSUE TITLE
after write xlsx, /xl/calcChain.xml will be lose

### ISSUE THREAD

**Issue by liufeijin** [j2doll/QXlsx#24]
after write xlsx, /xl/calcChain.xml whole  will be lose.
the row as below will be lose also in /[Content_Types].xml  
"  Override ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.calcChain+xml" PartName="/xl/calcChain.xml"/  “

**Comment by j2doll** [comment]
Dear @liufeijin 

I added code to append xl/calcChain.xml.

If you can test it, please try it.

https://github.com/j2doll/QXlsx/releases/tag/v1.3.11

**Comment by j2doll** [comment]
I'll close this issue.
