### ISSUE TITLE
Simple hello world program not working 

### ISSUE THREAD

**Issue by ShubhamParab** [j2doll/QXlsx#28]
Followed all installation steps 
& tried: https://github.com/j2doll/QXlsx/tree/master/HelloWorld code 
The program compiled successfully and stuck at console window
.xlsx file also not created

**Comment by j2doll** [comment]
Dear @ShubhamParab 

If you are using a shadow build on Qt, look for the corresponding xlsx file in the build- * path.

If the program runs normally, an xlsx file will be created.

**Comment by ShubhamParab** [comment]
No xlsx file in C:\Users\Shubham\Documents\QtProjects\build-HelloQXlsx-Desktop_Qt_5_10_1_MinGW_32bit-Release\release
while compiling: 
Project MESSAGE: QXLSX_PARENTPATH is not empty.
Project MESSAGE: ./
Project MESSAGE: QXLSX_HEADERPATH is not empty.
Project MESSAGE: ./header/
Project MESSAGE: QXLSX_SOURCEPATH is not empty.
Project MESSAGE: ./source/
Project MESSAGE: compiling for windows g++. mingw or msys or cygwin.
Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!
Project MESSAGE: QXLSX_PARENTPATH is not empty.
Project MESSAGE: ./
Project MESSAGE: QXLSX_HEADERPATH is not empty.
Project MESSAGE: ./header/
Project MESSAGE: QXLSX_SOURCEPATH is not empty.
Project MESSAGE: ./source/
Project MESSAGE: compiling for windows g++. mingw or msys or cygwin.
Project MESSAGE: QXLSX_PARENTPATH is not empty.
Project MESSAGE: ./
Project MESSAGE: QXLSX_HEADERPATH is not empty.
Project MESSAGE: ./header/
Project MESSAGE: QXLSX_SOURCEPATH is not empty.
Project MESSAGE: ./source/
Project MESSAGE: compiling for windows g++. mingw or msys or cygwin.

**Comment by j2doll** [comment]
Is it in debug mode? 
If you are in debug mode, see the debug path.

**Comment by ShubhamParab** [comment]
no, it's in release mode & 
\build-HelloQXlsx-Desktop_Qt_5_10_1_MinGW_32bit-Release\release have all the object files and executable 
\build-HelloQXlsx-Desktop_Qt_5_10_1_MinGW_32bit-Release\debug is empty

**Comment by j2doll** [comment]
Hi. @ShubhamParab 

:one: I have added debugging information for testing the HelloWorld example. 
 - [#02710b2](https://github.com/j2doll/QXlsx/commit/02710b254460e0299d59bc5a7b5f55dc4c747f02)

:two: I tested it on old Qt (5.0.2 / MingW32).

:three: The current (build) mode is the **release** mode.

:four: The test results are as follows.
```cmd
[debug] success to write xlsx file
[debug] current directory is  "C:/workspace/github/QXlsx/build-HelloWorld-Desktop_Qt_5_0_2_MinGW_32bit-Release"
[debug] success to load xlsx file.
QVariant(QString, "Hello Qt!")
Press <RETURN> to close this window...
```

:five: Check your **current** directory. 
- I think it may be 'build-HelloQXlsx-Desktop_Qt_5_10_1_MinGW_32bit-Release'
- And then look for the **Test.xlsx** file.

**Comment by ShubhamParab** [comment]
Thanks @j2doll
