### ISSUE TITLE
How to add to Qt?

### ISSUE THREAD

**Issue by tarzan115** [j2doll/QXlsx#3]
can you please make a video or a tutorial how to use it. I had tried but too hard to use it.
thank you so much.

**Comment by j2doll** [comment]
Hi, nice to meet you. 
I'll post a video or image for you to set up, soon.
And my native language is not engilsh, 
Please understand if I misunderstood the explanation :-)

**Comment by tarzan115** [comment]
thank you 😄

**Comment by j2doll** [comment]
See [https://github.com/j2doll/QXlsx/blob/master/HowToSetProject.md](https://github.com/j2doll/QXlsx/blob/master/HowToSetProject.md)
I hope it will be of help. 
If you are proficient in English, you can request to write the correct instructions.
Have a good time!
